application: suzukihideki1
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: index.php

env_variables:
 DEVELOPMENT_DB_HOST: ''
 DEVELOPMENT_DB_USERNAME: 'root'
 DEVELOPMENT_DB_PASSWORD: ''
 DEVELOPMENT_DB_NAME: 'suzukihideki1'
 PRODUCTION_CLOUD_SQL_INSTANCE: '/cloudsql/suzukihideki1:my-cloudsql-instance'
 PRODUCTION_DB_USERNAME: ''
 PRODUCTION_DB_PASSWORD: ''
 PRODUCTION_DB_NAME: 'suzukihideki1'
